---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-mongo-service
  labels:
    name: sandbox-mongo-service
spec:
  type: NodePort
  selector:
    app: sandbox-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-mongo-express-service
  labels:
    name: sandbox-mongo-express-service
spec:
  type: NodePort
  selector:
    app: sandbox-mongo-express
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-mongo-express-deployment
  labels:
    app: sandbox-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-mongo-express
  template:
    metadata:
      labels:
        app: sandbox-mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        imagePullPolicy: IfNotPresent
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "admin"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "admin"
        - name: ME_CONFIG_MONGODB_SERVER
          value: "sandbox-mongo-service.default"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-mongo-deployment
  labels:
    app: sandbox-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-mongo
  template:
    metadata:
      labels:
        app: sandbox-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.0
        ports:
        - containerPort: 27017
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "admin"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"       