---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-mongo-service
  labels:
    name: sandbox-mongo-service
spec:
  type: NodePort
  selector:
    app: sandbox-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30007

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-mongo-deployment
  labels:
    app: sandbox-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-mongo
  template:
    metadata:
      labels:
        app: sandbox-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.0
        ports:
        - containerPort: 27017
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "admin"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        
