---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-mysql-service
  labels:
    name: sandbox-mysql-service
spec:
  type: NodePort
  selector:
    app: sandbox-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30006

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-mysql-deployment
  labels:
    app: sandbox-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-mysql
  template:
    metadata:
      labels:
        app: sandbox-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_DATABASE
          value: "test"
