---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-postgres-service
  labels:
    name: sandbox-postgres-service
spec:
  type: NodePort
  selector:
    app: sandbox-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-postgres-deployment
  labels:
    app: sandbox-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-postgres
  template:
    metadata:
      labels:
        app: sandbox-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11
        ports:
        - containerPort: 5432
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: "admin"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_DB
          value: "test"
        
